# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  customer:
    description: |
      Name of the customer that will be added as label to collected metrics. It's useful when
      Prometheus collects metrics from multiple organizations/customers.
    default: ""
    type: string
  cloud-name:
    description: |
      Arbitrary name for a cloud/deployment. This name will be added as label to collected
      metrics. It's useful when Prometheus collects metrics from multiple controllers.
    default: ""
    type: string
  controller-url:
    description: Endpoint of a juju controller in format <IP>:<PORT>
    default: ""
    type: string
  controller-ca-cert:
    description: |
      This option is necessary only if if this exporter targets external controller (i.e.
      different controller than one deploying this charm). It should contain `base64` encoded
      CA certificate of the targeted juju controller.
    default: ""
    type: string
  juju-user:
    description: Username that will be used to log into juju controller
    default: ""
    type: string
  juju-password:
    description: Password for juju user
    default: ""
    type: string
  scrape-port:
    description: Port to which prometheus exporter is bound.
    default: 5000
    type: int
  scrape-interval:
    description: |
      This option dictates how often exporter updates its data and how often should Prometheus
      scrape them.(In minutes)
    default: 15
    type: int
  scrape-timeout:
    description: |
      How long should Prometheus wait for response to scrape request before timing out (In seconds)
    default: 30
    type: int
  virtual-macs:
    description: |
      The list of MAC address prefixes to be considered as virtual machines.
      The default value contains some of the most common MAC prefixes seen in
      virtual environment (QEMU, Microsoft, and VMWare).
      This configuration accepts comma-separated MAC prefixes in string format.
    default: "52:54:00,fa:16:3e,06:f1:3a,00:0d:3a,00:50:56"
    type: string
  match-interfaces:
    description: |
      Interface names that should be considered when detecting machine type. This
      option takes a regular expression that should match "real" interfaces on the machines.
      Usage of this option prevents virtual interfaces like 'virbr0' from being considered,
      avoiding physical machines to be potentially mislabeled as VM guests.
      Leaving this option empty will default to matching all interfaces.
    default: "^(en[os]|eth)\\d+|enp\\d+s\\d+|enx[0-9a-f]+"
    type: string
