name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-unit:
    uses: canonical/bootstack-actions/.github/workflows/lint-unit.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10']
    with:
      python-version: ${{ matrix.python-version }}

  func:
    uses: canonical/bootstack-actions/.github/workflows/func.yaml@v2
    needs: lint-unit
    strategy:
      fail-fast: false
      matrix:
        juju-channel: ['3.4/stable']
        command: ['TEST_JUJU3=1 make functional']

    with:
      command: TEST_JUJU_CHANNEL=${{ matrix.juju-channel }} ${{ matrix.command }}
      juju-channel: ${{ matrix.juju-channel }}
      nested-containers: true
      provider: 'lxd'
      python-version: '3.10'
      timeout-minutes: 120
